Jeoffrey Fischer --- Create SSW People Profile
SSWConsulting/SSW.People.Profiles pull request #1027
Opened 2023-10-16 23:26 UTC by jeoffreyfischer

Created the SSW People Profile page with the following : 
- id
- quote
- bio
- audio

2023-10-16 23:35 UTC, bradystroud requested changes

2023-10-16 23:35 UTC, bradystroud commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
Use markdown to bold text 
https://www.markdownguide.org/basic-syntax/#bold

2023-10-16 23:35 UTC, bradystroud commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
> +qualifications: ""
I would add your plane noise degree here

2023-10-16 23:35 UTC, JeanThirion commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
`With a strong foundation in Aeroacoustics, he previously served as an esteemed Aeroacoustics Lecturer at UNSW for eight years`

Aeroacoustics twice - also I'm pretty sure it's more than just "strong foundation ;D"

2023-10-16 23:35 UTC, JeanThirion commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
I'd also add a line break between intro (non-tech) and the tech part

2023-10-16 23:56 UTC, jeoffreyfischer commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
Done - thanks for that !

2023-10-16 23:57 UTC, jeoffreyfischer commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
> +qualifications: ""
Done

2023-10-16 23:58 UTC, jeoffreyfischer commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
Done - sentence removed and added line breaks

2023-10-17 00:07 UTC, bradystroud commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
> +[Editing your profile]: https://github.com/SSWConsulting/People/wiki/3.-Editing-your-profile
remove this

2023-10-17 00:09 UTC, jeoffreyfischer commented on Jeoffrey-Fischer/Jeoffrey-Fischer.md
> +[Editing your profile]: https://github.com/SSWConsulting/People/wiki/3.-Editing-your-profile
Done

2023-10-17 00:10 UTC, bradystroud approved these changes

2023-10-17 00:10 UTC, merged