Yalal Cakir - Initializing the SSW People Profile
SSWConsulting/SSW.People.Profiles pull request #1076
Opened 2023-12-22 04:36 UTC by YalalCakirSSW

Pictures and small paragraph about me is added

2023-12-22 05:46 UTC, bradystroud requested changes

2023-12-22 05:46 UTC, bradystroud commented on Yalal-Cakir/Yalal-Cakir.md
Hey Yalal, this is really short.

Maybe add some detail.

- Any personal projects?
- Key skills?
- Hobbies?
- Passions?
- contributions?

2023-12-26 22:31 UTC, YalalCakirSSW commented on Yalal-Cakir/Yalal-Cakir.md
Done. - I added some details.

2023-12-27 00:32 UTC, bradystroud approved these changes

2023-12-27 00:32 UTC, merged