Add files via upload
SSWConsulting/SSW.People.Profiles pull request #506
Opened 2021-06-03 00:07 UTC by taqwahasyimssw

2021-06-03 00:31 UTC, MattGoldmanSSW approved these changes

2021-06-03 00:31 UTC, MattGoldmanSSW approved these changes

2021-06-04 00:19 UTC, pierssinclairssw requested changes
The profile images should be in an images folder under the folder with your name. If you need help then contact me :)

2021-06-07 23:36 UTC, christianmorfordwaitessw commented
Images have already been updated, closing the PR

2021-06-07 23:36 UTC, closed without merging