Adding Jack's profile to website
SSWConsulting/SSW.People.Profiles pull request #600
Opened 2022-02-23 06:22 UTC by duanxinhuan

Hi Morford,
Please Check my profile and if you are happy you can add me.

2022-02-23 06:30 UTC, christianmorfordwaitessw commented
Hi @duanxinhuan, 

1. Can you please send your images to a designer to get them formatted correctly. 
Please follow the instructions here [Get and use your official SSW profile photo](https://my.sugarlearning.com/SSW/items/9368/get-and-use-your-official-ssw-profile-photo?term=photos).

2022-02-23 06:37 UTC, christianmorfordwaitessw commented on Jack-Duan/Jack-Duan.md
> +[Design Guidelines](https://www.ssw.com.au/ssw/logo/ssw/)
Remove the design guidelines link

2022-03-02 03:39 UTC, duanxinhuan commented
Hi anyone can review this one for me?

2022-03-02 23:21 UTC, pierssinclairssw requested changes

2022-03-02 23:21 UTC, pierssinclairssw commented on Jack-Duan/Jack-Duan.md
> +His skill sets are:
change to either

His skill set includes:

or

His skills include:

2022-03-02 23:21 UTC, pierssinclairssw commented on Jack-Duan/Jack-Duan.md
> +* .NET framework.
I recommend you change this to .NET

.NET framework is quite old now.

2022-03-02 23:21 UTC, pierssinclairssw commented on Jack-Duan/Jack-Duan.md
> +In his spare time, he also makes fancy jewellery which he can sell you if you want :)
you need a to after sell

"which he can sell to you if you want"

2022-03-02 23:21 UTC, pierssinclairssw commented on Jack-Duan/Jack-Duan.md
> +[Editing your profile]: https://github.com/SSWConsulting/People/wiki/3.-Editing-your-profile
I think you want to get rid of this line

2022-03-02 23:23 UTC, closed without merging