Improved Markdown Jernej-Kavka.md
SSWConsulting/SSW.People.Profiles pull request #934
Opened 2023-06-13 17:14 UTC by tiagov8

2023-06-13 23:15 UTC, jernejk requested changes
Just needs these changes, so that alt text is correct.

2023-06-13 23:15 UTC, jernejk commented on Jernej-Kavka/Jernej-Kavka.md
> +| ![](../badges/Developer-dotnet-foundation.png)
```suggestion
| ![.NET Foundation](../badges/Developer-dotnet-foundation.png)
```

2023-06-13 23:15 UTC, jernejk commented on Jernej-Kavka/Jernej-Kavka.md
> +| ![](../badges/Event-global-ai-community.jpg)
```suggestion
| ![Global AI Community](../badges/Event-global-ai-community.jpg)
```

2023-06-13 23:15 UTC, jernejk commented on Jernej-Kavka/Jernej-Kavka.md
> +| ![.NET](../badges/Developer-dotnet-machine-learning.png)
```suggestion
| ![ML.NET](../badges/Developer-dotnet-machine-learning.png)
```

2023-06-14 03:30 UTC, bradystroud approved these changes

2023-06-14 03:51 UTC, jernejk approved these changes
LGTM

2023-06-14 05:12 UTC, merged